#!/usr/bin/env python3
import csv
import gzip
import json
import re
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data/output"
CLIENT_DB = ROOT / "data/client_export/udise_schools_client.sqlite3"
OUTPUT = ROOT / "data/client_export/ezy_yellowslate_unified_all_cities.csv"
COMPRESSED = ROOT / "data/client_export/ezy_yellowslate_unified_all_cities.csv.gz"
BENGALURU_SOURCE = Path("/Users/malleswararao/Desktop/BangaloreRancho/web_platform_vercel_exact_latest/src/public/data/schools.json")

CITY_FILES = {
    "chennai": DATA / "schools_merged_all_candidates_chennai.json",
    "delhi_ncr": DATA / "schools_merged_all_candidates_delhi_ncr.json",
    "hyderabad": DATA / "schools_merged_all_candidates_hyderabad.json",
    "kolkata": DATA / "schools_merged_all_candidates_kolkata.json",
    "mumbai": DATA / "schools_merged_all_candidates_mumbai.json",
    "pune": DATA / "schools_merged_all_candidates_pune.json",
}

COLUMNS = [
    "school_name", "normalized_name", "city", "area", "address", "pincode",
    "latitude", "longitude", "coordinate_source", "boards", "fee", "fee_min",
    "fee_max", "fee_text", "lowest_class", "highest_class", "offered_classes",
    "student_enrollment", "student_enrollment_grades_2_9", "enrollment_source",
    "udise_code", "udise_school_name", "match_status", "ezyschooling_url",
    "yellowslate_url", "primary_url", "source", "source_cities", "category",
    "zone", "data_quality_notes",
]


def text(value):
    return str(value or "").strip()


def normalize_name(value):
    value = text(value).lower()
    return re.sub(r"[^a-z0-9]", "", value)


def fee_value(value):
    if isinstance(value, dict):
        low, high = value.get("min_fee"), value.get("max_fee")
        numbers = [float(x) for x in (low, high) if isinstance(x, (int, float)) and x > 0]
        return round(sum(numbers) / len(numbers), 2) if numbers else ""
    return value if isinstance(value, (int, float)) and value > 0 else ""


def fee_details(value):
    if not isinstance(value, dict):
        return fee_value(value), "", "", ""
    low, high = value.get("min_fee"), value.get("max_fee")
    return fee_value(value), low or "", high or "", text(value.get("fee_text"))


def source_value(row):
    has_ezy = bool(row.get("ezyschooling_url"))
    has_yellow = bool(row.get("yellowslate_url"))
    if has_ezy and has_yellow:
        return "both"
    if has_ezy:
        return "ezyschooling"
    if has_yellow:
        return "yellowslate"
    return text(row.get("source"))


def quality_notes(row, fee):
    notes = []
    for field in ("address", "pincode"):
        if not text(row.get(field)):
            notes.append(f"missing_{field}")
    if fee == "":
        notes.append("missing_fee")
    if not text(row.get("udise_code")):
        notes.append("unmatched_udise")
    raw_fee = row.get("fee")
    if isinstance(raw_fee, dict) and raw_fee.get("min_fee") != raw_fee.get("max_fee"):
        notes.append("fee_is_range_average")
    return "|".join(notes)


def merge_prefer(existing, incoming):
    """Conservatively merge duplicate records without replacing populated values."""
    for key, value in incoming.items():
        if key == "source_cities":
            cities = set(filter(None, existing[key].split("|"))) | set(filter(None, value.split("|")))
            existing[key] = "|".join(sorted(cities))
        elif key == "source":
            sources = {existing[key], value} - {""}
            existing[key] = "both" if len(sources) > 1 or "both" in sources else next(iter(sources), "")
        elif not existing.get(key) and value:
            existing[key] = value
    return existing


def main():
    udise_names = {}
    if CLIENT_DB.exists():
        db = sqlite3.connect(f"file:{CLIENT_DB}?mode=ro", uri=True)
        udise_names = dict(db.execute("SELECT udise_code,school_name FROM schools"))
        db.close()

    unified = {}
    source_rows = 0
    for city, path in CITY_FILES.items():
        # These final files were generated by predict_enrollment_and_compile.py,
        # which clears old coordinates and geocodes every retained row via Google.
        final_path = DATA / f"schools_{city}_final.json"
        final_rows = json.loads(final_path.read_text(encoding="utf-8")) if final_path.exists() else []
        final_by_udise = {text(x.get("udise_code")): x for x in final_rows if text(x.get("udise_code"))}
        final_by_name = {normalize_name(x.get("name")): x for x in final_rows if normalize_name(x.get("name"))}
        for row in json.loads(path.read_text(encoding="utf-8")):
            try:
                if str(row.get("highest_class") or "").strip() and float(row["highest_class"]) < 2:
                    continue
            except (TypeError, ValueError):
                pass
            source_rows += 1
            name = text(row.get("school_name"))
            normalized = normalize_name(name)
            pincode = text(row.get("pincode"))
            area = text(row.get("area"))
            udise_code = text(row.get("udise_code"))
            fee, fee_min, fee_max, fee_text = fee_details(row.get("fee"))
            final = final_by_udise.get(udise_code) or final_by_name.get(normalize_name(name)) or {}
            latitude = final.get("lat") if final.get("lat") is not None else row.get("latitude")
            longitude = final.get("lon") if final.get("lon") is not None else row.get("longitude")
            if final.get("lat") is not None and final.get("lon") is not None:
                coordinate_source = "google_maps_api"
            elif latitude is not None and longitude is not None:
                coordinate_source = source_value(row)
            else:
                coordinate_source = ""
            boards = row.get("boards") or []
            if isinstance(boards, str):
                boards = [boards]
            boards = "|".join(dict.fromkeys(text(x) for x in boards if text(x)))
            record = {
                "school_name": name,
                "normalized_name": normalized,
                "city": city,
                "area": area,
                "address": text(row.get("address")),
                "pincode": pincode,
                "latitude": latitude if latitude is not None else "",
                "longitude": longitude if longitude is not None else "",
                "coordinate_source": coordinate_source,
                "boards": boards,
                "fee": fee,
                "fee_min": fee_min,
                "fee_max": fee_max,
                "fee_text": fee_text,
                "lowest_class": row.get("lowest_class") if row.get("lowest_class") is not None else "",
                "highest_class": row.get("highest_class") if row.get("highest_class") is not None else "",
                "offered_classes": text(row.get("offered_classes")),
                "student_enrollment": row.get("student_enrollment") or "",
                "student_enrollment_grades_2_9": row.get("student_enrollment_grades_2_9") or "",
                "enrollment_source": text(row.get("enrollment_source")),
                "udise_code": udise_code,
                "udise_school_name": text(udise_names.get(udise_code)),
                "match_status": "matched" if udise_code else "unmatched",
                "ezyschooling_url": text(row.get("ezyschooling_url")),
                "yellowslate_url": text(row.get("yellowslate_url")),
                "primary_url": text(final.get("url")) or text(row.get("ezyschooling_url")) or text(row.get("yellowslate_url")),
                "source": source_value(row),
                "source_cities": city,
                "category": text(final.get("category")),
                "zone": text(final.get("zone")),
                "data_quality_notes": quality_notes(row, fee),
            }
            # UDISE is strongest; otherwise require same normalized name and city,
            # with PIN or area preventing unrelated branches from collapsing.
            key = ("udise", udise_code) if udise_code else (
                "source", city, normalized, pincode or area.lower()
            )
            if key in unified:
                merge_prefer(unified[key], record)
            else:
                unified[key] = record

    if BENGALURU_SOURCE.exists():
        for row in json.loads(BENGALURU_SOURCE.read_text(encoding="utf-8")):
            source_rows += 1
            name = text(row.get("name"))
            normalized = normalize_name(name)
            pincode = text(row.get("pincode") or row.get("google_postal_code"))
            fee = row.get("fee") if isinstance(row.get("fee"), (int, float)) else ""
            fee_min = row.get("fee_min") if isinstance(row.get("fee_min"), (int, float)) else ""
            fee_max = row.get("fee_max") if isinstance(row.get("fee_max"), (int, float)) else ""
            record = {
                "school_name": name,
                "normalized_name": normalized,
                "city": "bengaluru",
                "area": text(row.get("area")),
                "address": text(row.get("address") or row.get("google_formatted_address")),
                "pincode": pincode,
                "latitude": row.get("lat") if row.get("lat") is not None else "",
                "longitude": row.get("lon") if row.get("lon") is not None else "",
                "coordinate_source": "google_maps_api" if row.get("lat") is not None and row.get("lon") is not None else "",
                "boards": text(row.get("board")).replace("/", "|"),
                "fee": fee,
                "fee_min": fee_min,
                "fee_max": fee_max,
                "fee_text": text(row.get("fee_text")),
                "lowest_class": "",
                "highest_class": "",
                "offered_classes": text(row.get("structural_category")),
                "student_enrollment": row.get("students_total") or row.get("students") or "",
                "student_enrollment_grades_2_9": row.get("students_grades_2_9") or "",
                "enrollment_source": text(row.get("enrollment_source")),
                "udise_code": text(row.get("udise_code")),
                "udise_school_name": "",
                "match_status": "matched" if text(row.get("udise_code")) else text(row.get("match_status")) or "unmatched",
                "ezyschooling_url": text(row.get("url")) if "ezyschooling" in text(row.get("url")) else "",
                "yellowslate_url": text(row.get("url")) if "yellowslate" in text(row.get("url")) else "",
                "primary_url": text(row.get("url")),
                "source": text(row.get("source")),
                "source_cities": "bengaluru",
                "category": text(row.get("category")),
                "zone": text(row.get("zone")),
                "data_quality_notes": "",
            }
            key = ("udise", record["udise_code"]) if record["udise_code"] else (
                "source", "bengaluru", normalized, pincode or text(row.get("area")).lower()
            )
            if key in unified:
                merge_prefer(unified[key], record)
            else:
                unified[key] = record

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    records = sorted(unified.values(), key=lambda x: (x["city"], x["school_name"].lower(), x["pincode"]))
    with open(OUTPUT, "w", newline="", encoding="utf-8-sig") as output:
        writer = csv.DictWriter(output, fieldnames=COLUMNS)
        writer.writeheader()
        writer.writerows(records)
    with open(OUTPUT, "rb") as source, gzip.open(COMPRESSED, "wb", compresslevel=9) as target:
        while chunk := source.read(1024 * 1024):
            target.write(chunk)

    print(f"Input rows: {source_rows:,}")
    print(f"Unified rows: {len(records):,}")
    print(f"Matched UDISE: {sum(bool(x['udise_code']) for x in records):,}")
    print(f"Both sources: {sum(x['source']=='both' for x in records):,}")
    print(f"CSV: {OUTPUT} ({OUTPUT.stat().st_size / 1024 / 1024:.1f} MB)")
    print(f"Gzip: {COMPRESSED} ({COMPRESSED.stat().st_size / 1024 / 1024:.1f} MB)")


if __name__ == "__main__":
    main()
