import os

generator_path = "/Users/malleswararao/Desktop/CatchmentIQ/catchmentiq/output/generator.py"

with open(generator_path, "r") as f:
    lines = f.readlines()

keep_lines = []
for line in lines:
    keep_lines.append(line)
    if "hotspots_json_str = json.dumps(hotspots_list)" in line:
        break

new_implementation = """
    # Locate templates directory
    templates_dir = os.path.join(os.path.dirname(__file__), "templates")
    
    # Read modular template files
    with open(os.path.join(templates_dir, "index.html"), "r") as f:
        index_html = f.read()
    with open(os.path.join(templates_dir, "swiss.css"), "r") as f:
        swiss_css = f.read()
    with open(os.path.join(templates_dir, "App.js"), "r") as f:
        app_js = f.read()
    with open(os.path.join(templates_dir, "Sidebar.js"), "r") as f:
        sidebar_js = f.read()
    with open(os.path.join(templates_dir, "MapComponent.js"), "r") as f:
        map_component_js = f.read()
    with open(os.path.join(templates_dir, "AuditPanel.js"), "r") as f:
        audit_panel_js = f.read()

    # 1. Output Modular Bundle inside bundle_dir
    os.makedirs(os.path.join(bundle_dir, "css"), exist_ok=True)
    os.makedirs(os.path.join(bundle_dir, "js"), exist_ok=True)
    os.makedirs(os.path.join(bundle_dir, "js", "components"), exist_ok=True)

    # Write CSS and component files
    with open(os.path.join(bundle_dir, "css", "swiss.css"), "w") as f:
        f.write(swiss_css)
    with open(os.path.join(bundle_dir, "js", "App.js"), "w") as f:
        f.write(app_js)
    with open(os.path.join(bundle_dir, "js", "components", "Sidebar.js"), "w") as f:
        f.write(sidebar_js)
    with open(os.path.join(bundle_dir, "js", "components", "MapComponent.js"), "w") as f:
        f.write(map_component_js)
    with open(os.path.join(bundle_dir, "js", "components", "AuditPanel.js"), "w") as f:
        f.write(audit_panel_js)
    
    # Write data.js containing coordinates and geometries
    data_js_content = f\"\"\"// Dynamic Data Variables generated by CatchmentIQ pipeline
window.gridData = {grid_geojson_str};
window.schoolsData = {schools_json_str};
window.listingsData = {listings_json_str};
window.hotspotsData = {hotspots_json_str};
window.runTargetBracket = "{run_bracket}";
\"\"\"
    with open(os.path.join(bundle_dir, "js", "data.js"), "w") as f:
        f.write(data_js_content)

    # Write modular index.html
    with open(os.path.join(bundle_dir, "index.html"), "w") as f:
        f.write(index_html)

    # 2. Output Standalone Single-File Bundle (catchment_analyzer.html)
    # Replace stylesheets and scripts with inlined contents for direct file:// browsing without CORS issues
    standalone_html = index_html
    
    # Inline CSS
    standalone_html = standalone_html.replace(
        '<link rel="stylesheet" href="css/swiss.css" />',
        f"<style>\\n{swiss_css}\\n</style>"
    )
    
    # Inline Data JS
    standalone_html = standalone_html.replace(
        '<script src="js/data.js"></script>',
        f"<script>\\n{data_js_content}\\n</script>"
    )
    
    # Inline JS components
    standalone_html = standalone_html.replace(
        '<script type="text/babel" src="js/components/Sidebar.js"></script>',
        f'<script type="text/babel">\\n{sidebar_js}\\n</script>'
    )
    standalone_html = standalone_html.replace(
        '<script type="text/babel" src="js/components/MapComponent.js"></script>',
        f'<script type="text/babel">\\n{map_component_js}\\n</script>'
    )
    standalone_html = standalone_html.replace(
        '<script type="text/babel" src="js/components/AuditPanel.js"></script>',
        f'<script type="text/babel">\\n{audit_panel_js}\\n</script>'
    )
    standalone_html = standalone_html.replace(
        '<script type="text/babel" src="js/App.js"></script>',
        f'<script type="text/babel">\\n{app_js}\\n</script>'
    )

    standalone_path = os.path.join(bundle_dir, "catchment_analyzer.html")
    with open(standalone_path, "w") as f:
        f.write(standalone_html)
        
    print(f"[OUTPUT] ✅ Modular Catchment Analyzer saved in: {bundle_dir}/")
    print(f"[OUTPUT] ✅ Standalone Catchment Analyzer saved: {standalone_path}")
"""

final_content = "".join(keep_lines) + new_implementation

with open(generator_path, "w") as f:
    f.write(final_content)

print("Generator file successfully rewritten.")
